### PR TITLE
New feature: inject exceptions within try-catch blocks #2

### PR DESCRIPTION
**Pull request by gluckzhang**
I added some features for byte-monkey: **throwing corresponding exceptions in the very beginning of try blocks**, to make this chaos engineering tool more powerful. It's also some relevant work about [short-circuit testing](http://blog.gluckzhang.com/archives/107/).

For this pull request, main updates are as follows:
 - new mode: `scircuit`, to throw corresponding exceptions in the very beginning of try blocks
 - new mode: `analyzetc`, analyze the try-catch blocks info in runtime
 - an example: take [spojo-core](https://github.com/sWoRm/Spojo) as an example to do some try-catch analysis, also involve another fancy tool called [Spoon](http://spoon.gforge.inria.fr/)

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @mrwilson ,
I created a specific branch for this pull request, please feel free to contact me if you have any suggestions about it :)

**Comment by gluckzhang** [comment]
I took [spojo-core](https://github.com/sWoRm/Spojo) as an example to show how to analyze try-catch blocks both in a static way and in runtime. But the directory of `example` might not be necessary to be merged, I can just add some commands / comments in `AnalyzeTCModelTest` and remove the example dir. What do you think of it?

**Comment by mrwilson** [comment]
Thanks! I'll take a look at these and add my thoughts

**Comment by mrwilson** [comment]
Thanks for all your work on this! I really like the `SCIRCUIT` mode, and am happy to merge those changes in - thanks for adding the corresponding tests in too.

The scope for the project is only to actually inject different failure modes, so it feels to me like the `ANALYZETC` mode, while useful, doesn't really fit.

If you're happy to split out these changes, that would be amazing, and I would merge them in asap :)

**Comment by gluckzhang** [comment]
Hi Alex, that's a good suggestion, `ANALYZETC` is indeed something else, but of which implementation was inspired by your code :)
And sure, I will update this branch tomorrow, to focus on `SCIRCUIT` mode.

**Comment by gluckzhang** [comment]
Hi @mrwilson , I have removed the relevant codes and docs about `ANALYZETC` mode, so this pr is specifically for short circuit mode now. Have a nice day!

**Comment by mrwilson** [comment]
This looks great! All tests are passing and I'm happy to merge this in :)

Thank you for the time and effort.

**Comment by gluckzhang** [comment]
Cheers! I will keep working on this, maybe get some new topics to discuss with you soon :)

**Pull request merged**
